from __future__ import annotations

import pprint
from collections import defaultdict

from .models import KINDS, Project, compile_locator

HEADER = "# Generated by MaaPlus Studio. Edit maaplus-studio.json instead.\n"
CONSTRUCTORS = {kind: cls.__name__ for kind, cls in KINDS.items()}


def generate(project: Project) -> dict[str, str]:
    """Produce deterministic standalone modules, expanding composition references inline."""
    modules = defaultdict(list)
    for group in project.groups:
        modules[group.module].append(group)
    output = {}
    for module, groups in sorted(modules.items()):
        imports = set()
        reserved = {g.class_name for g in groups} | {item.name for item in project.locators}
        aliases = {}
        for name in CONSTRUCTORS.values():
            alias = name
            while alias in reserved:
                alias = "_studio_" + alias
            aliases[name] = alias
            reserved.add(alias)

        def expression(item) -> str:
            constructor = CONSTRUCTORS[item.kind]
            alias = aliases[constructor]
            imports.add(constructor if alias == constructor else f"{constructor} as {alias}")
            native = compile_locator(project, item.id)
            names = {"all_of", "box_index"} if item.kind == "And" else {"any_of"} if item.kind == "Or" else set(item.params)
            args = []
            for name in sorted(names):
                value = pprint.pformat(getattr(native, name), width=80, sort_dicts=True)
                args.append(f"{name}={value}".replace("\n", "\n        "))
            if not args:
                return f"{alias}()"
            return f"{alias}(\n" + "".join(f"        {arg},\n" for arg in args) + "    )"

        bodies = []
        for group in sorted(groups, key=lambda value: value.class_name):
            entries = sorted((item for item in project.locators if item.group_id == group.id and item.export), key=lambda item: item.name)
            body = f"class {group.class_name}:\n"
            body += "\n".join(f"    {item.name} = {expression(item)}\n" for item in entries) if entries else "    pass\n"
            bodies.append(body)
        source = HEADER + "\n" + (f"from maa.pipeline import {', '.join(sorted(imports))}\n" if imports else "")
        source += "\n\n" + "\n\n".join(bodies)
        path = f"{project.output_dir.rstrip('/')}/{module.replace('.', '/')}.py"
        compile(source, path, "exec")
        output[path] = source
    return output
