import * as React from 'react';
import {
  Code,
  Copy,
  Check,
  Save,
  Download,
  Upload,
  FileCode,
} from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { UIClass } from '../types';

interface CodePreviewProps {
  uiClasses: UIClass[];
  selectedClassIndex: number;
  onSaveUiFile: (filePath: string, code: string) => Promise<boolean>;
  onImportClasses: (classes: UIClass[]) => void;
}

export function CodePreview({
  uiClasses,
  selectedClassIndex,
  onSaveUiFile,
  onImportClasses,
}: CodePreviewProps) {
  const [selectedClassScope, setSelectedClassScope] = React.useState<'active' | 'all'>('active');
  const [copied, setCopied] = React.useState(false);
  const [filePath, setFilePath] = React.useState('src/my_game/ui.py');
  const [isSaving, setIsSaving] = React.useState(false);
  const [statusMsg, setStatusMsg] = React.useState<string | null>(null);

  const importInputRef = React.useRef<HTMLInputElement>(null);

  // Generate Python code
  const generatedCode = React.useMemo(() => {
    const classesToRender =
      selectedClassScope === 'active' && uiClasses[selectedClassIndex]
        ? [uiClasses[selectedClassIndex]]
        : uiClasses;

    let code = `"""
MaaPlus UI Layer Definitions
Auto-generated by MaaPlus UI Workbench
"""

from maaplus.core.ui import UI, locator, action
from maaplus.core.controller import Controller

`;

    for (const cls of classesToRender) {
      code += `class ${cls.name}(UI):\n`;
      if (cls.locators.length === 0) {
        code += `    pass\n\n`;
        continue;
      }

      for (const loc of cls.locators) {
        if (loc.type === 'Template') {
          const tpl =
            loc.template && loc.template[0]
              ? `"${loc.template[0]}"`
              : `"${loc.name}.png"`;
          const roiStr = loc.roi ? `, roi=(${loc.roi.join(', ')})` : '';
          const thStr =
            loc.threshold !== undefined && loc.threshold !== 0.85
              ? `, threshold=${loc.threshold}`
              : '';
          code += `    ${loc.name} = locator.template(${tpl}${roiStr}${thStr})\n`;
        } else {
          const exp =
            loc.expected && loc.expected.length > 0
              ? `"${loc.expected[0]}"`
              : `"${loc.name}"`;
          const roiStr = loc.roi ? `, roi=(${loc.roi.join(', ')})` : '';
          code += `    ${loc.name} = locator.ocr(${exp}${roiStr})\n`;
        }
      }

      // Add sample action template
      code += `\n    @action\n`;
      code += `    async def auto_click_first(self, ctrl: Controller):\n`;
      code += `        """Example action method"""\n`;
      if (cls.locators.length > 0) {
        code += `        await self.${cls.locators[0].name}.click(ctrl)\n`;
      } else {
        code += `        pass\n`;
      }
      code += `\n`;
    }

    return code.trim() + '\n';
  }, [uiClasses, selectedClassIndex, selectedClassScope]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveToFile = async () => {
    if (!filePath) return;
    setIsSaving(true);
    const ok = await onSaveUiFile(filePath, generatedCode);
    setIsSaving(false);
    if (ok) {
      setStatusMsg(`成功保存至 ${filePath}`);
      setTimeout(() => setStatusMsg(null), 3500);
    }
  };

  // Export Workbench JSON config
  const handleExportJson = () => {
    const jsonStr = JSON.stringify(uiClasses, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'maaplus_ui_config.json';
    a.click();
    URL.revokeObjectURL(url);
  };

  // Import Workbench JSON config
  const handleImportJson = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();
      reader.onload = (event) => {
        try {
          const parsed = JSON.parse(event.target?.result as string);
          if (Array.isArray(parsed)) {
            onImportClasses(parsed);
            setStatusMsg('成功导入 UI 配置文件！');
            setTimeout(() => setStatusMsg(null), 3500);
          }
        } catch {
          alert('JSON 解析失败，请检查文件格式');
        }
      };
      reader.readAsText(file);
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full bg-slate-950 p-6 overflow-y-auto space-y-4 select-none">
      {/* Header Toolbar */}
      <div className="flex items-center justify-between bg-slate-900/60 p-4 rounded-xl border border-slate-800">
        <div className="space-y-1">
          <h2 className="text-base font-bold text-slate-100 flex items-center space-x-2">
            <FileCode className="w-5 h-5 text-sky-400" />
            <span>Python UI 类代码生成 (Code Generation)</span>
          </h2>
          <p className="text-xs text-slate-400">
            根据画布中配置的定位符与 ROI 参数，实时生成强类型 MaaPlus UI 代码
          </p>
        </div>

        <div className="flex items-center space-x-2">
          {/* Scope switch */}
          <div className="flex items-center bg-slate-950 border border-slate-800 rounded-lg p-0.5">
            <button
              onClick={() => setSelectedClassScope('active')}
              className={`px-3 py-1 text-xs rounded-md font-medium transition-colors ${
                selectedClassScope === 'active'
                  ? 'bg-slate-800 text-sky-400 font-semibold'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              当前类 ({uiClasses[selectedClassIndex]?.name || 'None'})
            </button>
            <button
              onClick={() => setSelectedClassScope('all')}
              className={`px-3 py-1 text-xs rounded-md font-medium transition-colors ${
                selectedClassScope === 'all'
                  ? 'bg-slate-800 text-sky-400 font-semibold'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              全部类 ({uiClasses.length})
            </button>
          </div>

          <Button
            size="sm"
            onClick={handleCopy}
            className="h-8 text-xs bg-slate-800 hover:bg-slate-700 text-slate-200"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 mr-1 text-emerald-400" />
                <span className="text-emerald-400">已复制</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 mr-1" />
                <span>复制 Python 代码</span>
              </>
            )}
          </Button>

          {/* Export / Import JSON */}
          <Button
            size="sm"
            variant="outline"
            onClick={handleExportJson}
            className="h-8 text-xs text-slate-400 hover:text-slate-200"
            title="导出为 JSON 配置文件备份"
          >
            <Download className="w-3.5 h-3.5 mr-1" />
            <span>导出 JSON</span>
          </Button>

          <input
            type="file"
            ref={importInputRef}
            onChange={handleImportJson}
            accept=".json"
            className="hidden"
          />
          <Button
            size="sm"
            variant="outline"
            onClick={() => importInputRef.current?.click()}
            className="h-8 text-xs text-slate-400 hover:text-slate-200"
            title="导入 JSON 配置文件"
          >
            <Upload className="w-3.5 h-3.5 mr-1" />
            <span>导入 JSON</span>
          </Button>
        </div>
      </div>

      {/* Save to Project File Bar */}
      <div className="flex items-center space-x-3 bg-slate-900/40 border border-slate-800 p-3 rounded-lg">
        <span className="text-xs text-slate-400 shrink-0">保存至工程文件:</span>
        <Input
          value={filePath}
          onChange={(e) => setFilePath(e.target.value)}
          placeholder="例如: src/my_game/ui.py"
          className="h-8 text-xs font-mono"
        />
        <Button
          size="sm"
          onClick={handleSaveToFile}
          disabled={isSaving}
          className="h-8 text-xs bg-sky-600 hover:bg-sky-500 text-white shrink-0"
        >
          <Save className="w-3.5 h-3.5 mr-1.5" />
          <span>{isSaving ? '保存中...' : '写入文件'}</span>
        </Button>
        {statusMsg && (
          <span className="text-xs text-emerald-400 font-medium animate-in fade-in">
            {statusMsg}
          </span>
        )}
      </div>

      {/* Code Editor / Viewer */}
      <div className="flex-1 bg-slate-950 border border-slate-800 rounded-xl overflow-hidden flex flex-col">
        <div className="bg-slate-900/80 px-4 py-2 border-b border-slate-800 flex items-center justify-between text-xs text-slate-400 font-mono">
          <span>Python 3.10+ · MaaPlus UI Definition</span>
          <span>UTF-8</span>
        </div>
        <div className="flex-1 p-4 overflow-auto font-mono text-xs leading-relaxed text-sky-200/90 bg-[#0d1117] selection:bg-sky-900/50">
          <pre id="codePreviewBox" className="whitespace-pre">{generatedCode}</pre>
        </div>
      </div>
    </div>
  );
}
