import { LocatorConfig, UIClass } from '../types';

export type DiagnosticSeverity = 'error' | 'warning' | 'info';

export interface CodeDiagnostic {
  severity: DiagnosticSeverity;
  message: string;
  className?: string;
  locatorName?: string;
}

export interface RenderedCode {
  code: string;
  diagnostics: CodeDiagnostic[];
}

function pythonString(value: string): string {
  return JSON.stringify(value).replace(/\\u2028|\\u2029/g, (match) =>
    match === '\\u2028' ? '\\u2028' : '\\u2029'
  );
}

function pythonList(values: string[]): string {
  return `[${values.map(pythonString).join(', ')}]`;
}

function pythonRoi(roi: LocatorConfig['roi']): string | null {
  if (!roi) return null;
  return `(${roi.map((value) => Math.max(0, Math.round(Number(value) || 0))).join(', ')})`;
}

function safeIdentifier(value: string): boolean {
  return /^[A-Za-z_]\w*$/.test(value);
}

function renderLocator(
  locator: LocatorConfig,
  className: string,
  diagnostics: CodeDiagnostic[]
): string {
  if (!safeIdentifier(locator.name)) {
    diagnostics.push({
      severity: 'error',
      message: `“${locator.name}” 不是合法的 Python 标识符。`,
      className,
      locatorName: locator.name,
    });
  }

  if (locator.type === 'Template') {
    const templates = Array.isArray(locator.template) ? locator.template.filter(Boolean) : [];
    if (templates.length === 0) {
      diagnostics.push({
        severity: 'warning',
        message: 'Template 尚未配置模板图片路径。',
        className,
        locatorName: locator.name,
      });
    }
    const args = [`template=${pythonList(templates.length ? templates : [`${locator.name}.png`])}`];
    const threshold = Number(locator.threshold ?? 0.85);
    args.push(`threshold=[${Number.isFinite(threshold) ? threshold : 0.85}]`);
    const roi = pythonRoi(locator.roi);
    if (roi) args.push(`roi=${roi}`);
    return `    ${locator.name} = Template(\n        ${args.join(',\n        ')},\n    )`;
  }

  if (locator.type === 'OCR') {
    const expected = Array.isArray(locator.expected) ? locator.expected.filter(Boolean) : [];
    if (expected.length === 0) {
      diagnostics.push({
        severity: 'warning',
        message: 'OCR 尚未配置 expected 文本。',
        className,
        locatorName: locator.name,
      });
    }
    const args = [`expected=${pythonList(expected)}`];
    const roi = pythonRoi(locator.roi);
    if (roi) args.push(`roi=${roi}`);
    return `    ${locator.name} = OCR(\n        ${args.join(',\n        ')},\n    )`;
  }

  if (typeof locator.source === 'string' && locator.source.trim()) {
    diagnostics.push({
      severity: 'info',
      message: `${locator.type} 由项目源码原样保留；可在 Code Studio 中继续编辑。`,
      className,
      locatorName: locator.name,
    });
    return `    ${locator.name} = ${locator.source.trim()}`;
  }

  diagnostics.push({
    severity: 'warning',
    message: `${locator.type} 暂无可视化生成器，已生成 TODO 占位。`,
    className,
    locatorName: locator.name,
  });
  return `    # TODO: configure ${locator.type}\n    ${locator.name} = None`;
}

export function renderMaaPlusUI(classes: UIClass[]): RenderedCode {
  const diagnostics: CodeDiagnostic[] = [];
  const usedTypes = new Set<string>();

  for (const cls of classes) {
    for (const locator of cls.locators) usedTypes.add(locator.type);
  }

  const maaplusImports = ['OCR', 'Template'].filter((name) => usedTypes.has(name));
  if (usedTypes.has('FirstOf')) maaplusImports.push('FirstOf');
  if (usedTypes.has('AllOf')) maaplusImports.push('AllOf');

  const lines: string[] = [
    '"""UI locators generated by MaaPlus UI Workbench.',
    '',
    'Review diagnostics in Code Studio before writing this file.',
    '"""',
    '',
  ];

  if (maaplusImports.length) {
    lines.push(`from maaplus import ${Array.from(new Set(maaplusImports)).sort().join(', ')}`);
  }
  if (usedTypes.has('JCustomRecognition')) {
    lines.push('from maa.pipeline import JCustomRecognition');
  }
  if (lines[lines.length - 1] !== '') lines.push('');

  for (const cls of classes) {
    if (!safeIdentifier(cls.name)) {
      diagnostics.push({
        severity: 'error',
        message: `类名“${cls.name}”不是合法的 Python 标识符。`,
        className: cls.name,
      });
    }

    lines.push(`class ${cls.name}:`);
    if (cls.locators.length === 0) {
      lines.push('    pass');
    } else {
      cls.locators.forEach((locator, index) => {
        if (index > 0) lines.push('');
        lines.push(renderLocator(locator, cls.name, diagnostics));
      });
    }
    lines.push('');
    lines.push('');
  }

  const code = `${lines.join('\n').trimEnd()}\n`;
  return { code, diagnostics };
}

export function suggestedUiPath(uiClass?: UIClass): string {
  if (uiClass?.sourceFile) return uiClass.sourceFile;
  if (!uiClass?.name) return 'ui/generated.py';
  const stem = uiClass.name
    .replace(/UI$/, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[^A-Za-z0-9_]+/g, '_')
    .toLowerCase() || 'generated';
  return `ui/${stem}.py`;
}
